spring:
  application:
    name: spring-ai-backend

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  server:
    port: 8083

server:
  port: 8081

AmanOpenAI:
  APIKey: ${Azure_API_Key}
  Endpoint: ${Azure_Endpoint}

logging:
  level:
    org.springframework: ERROR

neo4j:
  connection:
    uri: ${Connection_URL}
    username: ${Connection_Username}
    password: ${Connection_Password}

chatbot:
  model: gemini-2.5-flash-lite
  apiKey: ${Gemini_API_Key}
  endpoint: ${Gemini_Endpoint}
